//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKurganov_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentApartments
    {
        public int ID { get; set; }
        public int ApartmentID { get; set; }
        public int VisitorID { get; set; }
        public int QuantityDays { get; set; }
        public int StaffID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Apartments Apartments { get; set; }
        public virtual Staffs Staffs { get; set; }
        public virtual Visitors Visitors { get; set; }
    }
}
